/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculator;

import org.apache.commons.lang.StringUtils;

import java.util.Arrays;

/**
 * @author Camilo
 */
public class Calculator extends javax.swing.JFrame {

    double firstValue = 0;
    double secondValue = 0;
    String operation;
    boolean isCalculating;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelInformation = new javax.swing.JPanel();
        labelCalculatorTitle = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        panelNumericKeysComplete = new javax.swing.JPanel();
        panelNumericKeys = new javax.swing.JPanel();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttoThree = new javax.swing.JButton();
        buttonCero = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        panelOperations = new javax.swing.JPanel();
        buttonOperationDivide = new javax.swing.JButton();
        buttonOperationMultiply = new javax.swing.JButton();
        buttonOperationSubtract = new javax.swing.JButton();
        buttonOperationAdd = new javax.swing.JButton();
        buttonOperationEqual = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonClean = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 11, 38));

        panelInformation.setBackground(new java.awt.Color(30, 11, 38));

        labelCalculatorTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCalculatorTitle.setForeground(new java.awt.Color(219, 90, 244));
        labelCalculatorTitle.setText("Calculator");

        textField.setBackground(new java.awt.Color(222, 68, 242));
        textField.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textField.setForeground(new java.awt.Color(30, 11, 38));
        textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelInformationLayout = new javax.swing.GroupLayout(panelInformation);
        panelInformation.setLayout(panelInformationLayout);
        panelInformationLayout.setHorizontalGroup(
            panelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCalculatorTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInformationLayout.createSequentialGroup()
                .addComponent(textField)
                .addContainerGap())
        );
        panelInformationLayout.setVerticalGroup(
            panelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCalculatorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelNumericKeysComplete.setBackground(new java.awt.Color(30, 11, 38));

        panelNumericKeys.setBackground(new java.awt.Color(76, 27, 89));

        buttonSeven.setBackground(new java.awt.Color(76, 27, 89));
        buttonSeven.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonSeven.setForeground(new java.awt.Color(13, 13, 13));
        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonEight.setBackground(new java.awt.Color(76, 27, 89));
        buttonEight.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonEight.setForeground(new java.awt.Color(13, 13, 13));
        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonNine.setBackground(new java.awt.Color(76, 27, 89));
        buttonNine.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonNine.setForeground(new java.awt.Color(13, 13, 13));
        buttonNine.setText("9");
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        buttonFour.setBackground(new java.awt.Color(76, 27, 89));
        buttonFour.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonFour.setForeground(new java.awt.Color(13, 13, 13));
        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonFive.setBackground(new java.awt.Color(76, 27, 89));
        buttonFive.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonFive.setForeground(new java.awt.Color(13, 13, 13));
        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonSix.setBackground(new java.awt.Color(76, 27, 89));
        buttonSix.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonSix.setForeground(new java.awt.Color(13, 13, 13));
        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonOne.setBackground(new java.awt.Color(76, 27, 89));
        buttonOne.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOne.setForeground(new java.awt.Color(13, 13, 13));
        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonTwo.setBackground(new java.awt.Color(76, 27, 89));
        buttonTwo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonTwo.setForeground(new java.awt.Color(13, 13, 13));
        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttoThree.setBackground(new java.awt.Color(76, 27, 89));
        buttoThree.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttoThree.setForeground(new java.awt.Color(13, 13, 13));
        buttoThree.setText("3");
        buttoThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoThreeActionPerformed(evt);
            }
        });

        buttonCero.setBackground(new java.awt.Color(76, 27, 89));
        buttonCero.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonCero.setForeground(new java.awt.Color(13, 13, 13));
        buttonCero.setText("0");
        buttonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCeroActionPerformed(evt);
            }
        });

        buttonPoint.setBackground(new java.awt.Color(119, 43, 188));
        buttonPoint.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonPoint.setForeground(new java.awt.Color(13, 13, 13));
        buttonPoint.setText(".");
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNumericKeysLayout = new javax.swing.GroupLayout(panelNumericKeys);
        panelNumericKeys.setLayout(panelNumericKeysLayout);
        panelNumericKeysLayout.setHorizontalGroup(
            panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNumericKeysLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNumericKeysLayout.createSequentialGroup()
                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNumericKeysLayout.createSequentialGroup()
                        .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNumericKeysLayout.createSequentialGroup()
                        .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonOne, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelNumericKeysLayout.createSequentialGroup()
                                .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttoThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelNumericKeysLayout.setVerticalGroup(
            panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNumericKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttoThree, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNumericKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelOperations.setBackground(new java.awt.Color(76, 27, 89));

        buttonOperationDivide.setBackground(new java.awt.Color(119, 43, 188));
        buttonOperationDivide.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOperationDivide.setForeground(new java.awt.Color(13, 13, 13));
        buttonOperationDivide.setText("÷");
        buttonOperationDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOperationDivideActionPerformed(evt);
            }
        });

        buttonOperationMultiply.setBackground(new java.awt.Color(119, 43, 188));
        buttonOperationMultiply.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOperationMultiply.setForeground(new java.awt.Color(13, 13, 13));
        buttonOperationMultiply.setText("x");
        buttonOperationMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOperationMultiplyActionPerformed(evt);
            }
        });

        buttonOperationSubtract.setBackground(new java.awt.Color(119, 43, 188));
        buttonOperationSubtract.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOperationSubtract.setForeground(new java.awt.Color(13, 13, 13));
        buttonOperationSubtract.setText("-");
        buttonOperationSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOperationSubtractActionPerformed(evt);
            }
        });

        buttonOperationAdd.setBackground(new java.awt.Color(119, 43, 188));
        buttonOperationAdd.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOperationAdd.setForeground(new java.awt.Color(13, 13, 13));
        buttonOperationAdd.setText("+");
        buttonOperationAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOperationAddActionPerformed(evt);
            }
        });

        buttonOperationEqual.setBackground(new java.awt.Color(0, 204, 0));
        buttonOperationEqual.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttonOperationEqual.setForeground(new java.awt.Color(0, 102, 0));
        buttonOperationEqual.setText("=");
        buttonOperationEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOperationEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperationsLayout = new javax.swing.GroupLayout(panelOperations);
        panelOperations.setLayout(panelOperationsLayout);
        panelOperationsLayout.setHorizontalGroup(
            panelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOperationEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(buttonOperationDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOperationMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOperationAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOperationSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOperationsLayout.setVerticalGroup(
            panelOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOperationDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOperationMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOperationSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOperationAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOperationEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelNumericKeysCompleteLayout = new javax.swing.GroupLayout(panelNumericKeysComplete);
        panelNumericKeysComplete.setLayout(panelNumericKeysCompleteLayout);
        panelNumericKeysCompleteLayout.setHorizontalGroup(
            panelNumericKeysCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumericKeysCompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNumericKeys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNumericKeysCompleteLayout.setVerticalGroup(
            panelNumericKeysCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelNumericKeysCompleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNumericKeysCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNumericKeys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(76, 27, 89));

        buttonClean.setBackground(new java.awt.Color(102, 0, 0));
        buttonClean.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonClean.setForeground(new java.awt.Color(255, 51, 51));
        buttonClean.setText("M");
        buttonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(102, 102, 0));
        buttonDelete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 0));
        buttonDelete.setText("DEL");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(buttonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNumericKeysComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumericKeysComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCeroActionPerformed
        textField.setText(textField.getText() + "0");
    }//GEN-LAST:event_buttonCeroActionPerformed


    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        textField.setText(textField.getText() + "1");
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        textField.setText(textField.getText() + "2");
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
    }//GEN-LAST:event_textFieldActionPerformed

    private void buttoThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoThreeActionPerformed
        textField.setText(textField.getText() + "3");
    }//GEN-LAST:event_buttoThreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        textField.setText(textField.getText() + "4");
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        textField.setText(textField.getText() + "5");
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        textField.setText(textField.getText() + "6");
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        textField.setText(textField.getText() + "7");
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        textField.setText(textField.getText() + "8");
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        textField.setText(textField.getText() + "9");
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        String stringToEvaluate = textField.getText();
        int comas = 0;
        for (int i = 0; i < stringToEvaluate.length(); i++) {
            char letter = stringToEvaluate.charAt(i);
            if (letter == '.') {
                comas++;
            }
        }
//        There is no comas
        if (comas == 0) {
            textField.setText(textField.getText() + ".");
        }


    }//GEN-LAST:event_buttonPointActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        textField.setText(StringUtils.chop(textField.getText()));
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyTyped
        int key = evt.getKeyChar();
        boolean numbers = key >= 48 && key <= 57;
        if (!numbers) {
            evt.consume();
        }

        if (textField.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldKeyTyped

    private void buttonOperationDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOperationDivideActionPerformed
        this.operation = "DIVIDE";
        this.firstValue = Double.parseDouble(textField.getText());
        textField.setText(null);
    }//GEN-LAST:event_buttonOperationDivideActionPerformed

    private void buttonOperationMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOperationMultiplyActionPerformed
        this.operation = "MULTIPLY";
        this.firstValue = Double.parseDouble(textField.getText());
        textField.setText(null);
    }//GEN-LAST:event_buttonOperationMultiplyActionPerformed

    private void buttonOperationSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOperationSubtractActionPerformed
        this.operation = "SUBTRACT";
        this.firstValue = Double.parseDouble(textField.getText());
        textField.setText(null);
    }//GEN-LAST:event_buttonOperationSubtractActionPerformed

    private void buttonOperationAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOperationAddActionPerformed
        this.operation = "ADD";
        this.firstValue = Double.parseDouble(textField.getText());
        textField.setText(null);
    }//GEN-LAST:event_buttonOperationAddActionPerformed


    private void buttonOperationEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOperationEqualActionPerformed
        this.secondValue = Double.parseDouble(textField.getText());
        String result;
        switch (operation) {
            case "DIVIDE":
                result = String.valueOf(firstValue / secondValue);
                textField.setText(deleteUnusedZeros(result));
                break;
            case "MULTIPLY":
                result = String.valueOf(firstValue * secondValue);
                textField.setText(deleteUnusedZeros(result));
                break;
            case "ADD":
                result = String.valueOf(firstValue + secondValue);
                textField.setText(deleteUnusedZeros(result));
                break;
            case "SUBTRACT":
                result = String.valueOf(firstValue - secondValue);
                textField.setText(deleteUnusedZeros(result));
                break;
            default:
                throw new AssertionError();
        }
        this.firstValue = 0;
        this.secondValue = 0;
    }//GEN-LAST:event_buttonOperationEqualActionPerformed

    private String deleteUnusedZeros(String number) {
        boolean thereIsComa = false;
        for (int i = 0; i < number.length() && !thereIsComa; i++) {
            if (number.charAt(i) == '.') {
                thereIsComa = true;
            }
        }

        String[] numberRaw = number.split("\\.");
        String toEvaluate = String.valueOf(numberRaw[1]);

        if(toEvaluate.length() == 1) {
            if (Integer.parseInt(toEvaluate) == 0) {
                return numberRaw[0];
            }
        }
        return number;
    }
    private void buttonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCleanActionPerformed
        this.firstValue = 0;
        this.secondValue = 0;
        this.operation = "";
        textField.setText(null);
    }//GEN-LAST:event_buttonCleanActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator calculator = new Calculator();
                calculator.setLocationRelativeTo(null);
                calculator.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoThree;
    private javax.swing.JButton buttonCero;
    private javax.swing.JButton buttonClean;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonOperationAdd;
    private javax.swing.JButton buttonOperationDivide;
    private javax.swing.JButton buttonOperationEqual;
    private javax.swing.JButton buttonOperationMultiply;
    private javax.swing.JButton buttonOperationSubtract;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCalculatorTitle;
    private javax.swing.JPanel panelInformation;
    private javax.swing.JPanel panelNumericKeys;
    private javax.swing.JPanel panelNumericKeysComplete;
    private javax.swing.JPanel panelOperations;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
